name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: Build with Docker
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nocturne-builder:latest .

      - name: Build Nocturne
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && \
          docker run --rm --privileged \
            --user 0:0 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            nocturne-builder:latest \
            /bin/bash -c "\
              cd /workspace/resources/stock-files && ./download.sh && \
              cd /workspace && \
              ./build.sh"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/**
