name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
